name: Build and deploy Node.js to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # path  to your project, usually the root
  NODE_VERSION: '18.x' # Since your dependencies like @azure/functions require node >=18

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: 'Setup Node.js ${{ env.NODE_VERSION }}'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the application
      - name: Build the application
        run: npm run build

      # Step 5: Zip artifact for deployment
      - name: Zip the project
        run: zip -r functionapp.zip .

      # Step 6: Upload the artifact for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: functionapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download the build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: function-app

      # Step 2: Unzip artifact
      - name: Unzip the project
        run: unzip functionapp.zip

      # Step 3: Deploy to Azure Function App
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'your-azure-function-app-name' # Replace with your Azure Function App name
          package: './functionapp.zip'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Make sure to set this in your GitHub repository's secrets
