name: Build and deploy Node.js project to Azure Function App - fs-bb-core-node

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './release.zip' # updated to match the path to the artifact created
  NODE_VERSION: '20.x' # Node.js version, adjust if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'fs-bb-core-node' # Azure Function App name
          slot-name: 'Production' # Slot name, can be 'staging' if needed
          package: './release.zip' # Path to the unzipped artifact
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_43DD7382CB6F4F89A666B18417E482B3 }} # Replace with your secret
